quak_shops_report:
    resource: "@QuakShopsReportBundle/Resources/config/routing.yml"
    prefix:   /report

quak_shops_admin:
    resource: "@QuakShopsAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

quak_shops_core:
    resource: "@QuakShopsCoreBundle/Resources/config/routing.yml"
    prefix:   /

