security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_SHOP:        ROLE_USER
        ROLE_ADMIN:       ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    shop:  { password: userpass, roles: [ 'ROLE_SHOP' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: _security_check
                login_path: login
            logout:
                path:   logout
                target: _demo

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/report, roles: ROLE_SHOP }
