security:
    encoders:
        Quak\ShopsCoreBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_SHOP:        ROLE_USER
        ROLE_ADMIN:       ROLE_USER

    providers:
        main:
            entity:
                class: Quak\ShopsCoreBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                csrf_provider: form.csrf_provider
            logout:
                path:   logout
                target: login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/report, roles: ROLE_SHOP }
        - { path: ^/, roles: ROLE_USER }
