homepage:
    pattern: /
    defaults: { _controller: QuakShopsCoreBundle:Access:index }

login:
    pattern:  /login
    defaults: { _controller: QuakShopsCoreBundle:Access:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout
