parameters:
    repository.user.class: Quak\ShopsCoreBundle\Repository\UserRepository
    repository.region.class: Quak\ShopsCoreBundle\Repository\RegionRepository
    repository.formField.class: Quak\ShopsCoreBundle\Repository\RegionRepository
    repository.shopReport.class: Quak\ShopsCoreBundle\Repository\ShopReportRepository
    repository.shopReportValue.class: Quak\ShopsCoreBundle\Repository\ShopReportValueRepository
    repository.scheduledReport.class: Quak\ShopsCoreBundle\Repository\ScheduledReportRepository
    repository.registryKey.class: Quak\ShopsCoreBundle\Repository\RegistryKeyRepository

    report.values.factory.class: Quak\ShopsCoreBundle\Services\ReportFormValuesFactory
    model.shopReport.class: Quak\ShopsCoreBundle\Services\ShopReportModel

services:
    #repositories
    repository.user:
        class: %repository.user.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ "QuakShopsCoreBundle:User" ]
    repository.region:
        class: %repository.region.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ "QuakShopsCoreBundle:Region" ]
    repository.formField:
        class: %repository.formField.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ "QuakShopsCoreBundle:FormField" ]
    repository.shopReport:
        class: %repository.shopReport.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ "QuakShopsCoreBundle:ShopReport" ]
    repository.shopReportValue:
        class: %repository.shopReportValue.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ "QuakShopsCoreBundle:ShopReportValue" ]
    repository.scheduledReport:
        class: %repository.scheduledReport.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ "QuakShopsCoreBundle:ScheduledReport" ]
    repository.registryKey:
        class: %repository.registryKey.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ "QuakShopsCoreBundle:RegistryKey" ]

    report.values.factory:
        class: %report.values.factory.class%
        arguments:
            manager: @doctrine.orm.entity_manager

    model.shopReport:
        class: %model.shopReport.class%
        arguments:
            manager: @doctrine.orm.entity_manager
            shopReportRepository: @repository.shopReport
            reportFormValuesFactory: @report.values.factory
