parameters:
    repository.user.class: Quak\ShopsCoreBundle\Repository\UserRepository
    repository.region.class: Quak\ShopsCoreBundle\Repository\RegionRepository

services:
    #repositories
    repository.user:
        class: %repository.user.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ "QuakShopsCoreBundle:User" ]
    repository.region:
        class: %repository.region.class%
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments: [ "QuakShopsCoreBundle:Region" ]
