parameters:
    reporter.xmlBuilder.class: Quak\ShopsAdminBundle\Report\XMLBuilder
    reporter.class: Quak\ShopsAdminBundle\Report\Reporter

services:
    reporter.xmlBuilder:
        class: %reporter.xmlBuilder.class%

    reporter:
        class: %reporter.class%
        arguments:
            manager: @doctrine.orm.entity_manager
            builder: @reporter.xmlBuilder
            mailer: @mailer
            source: %source_mail%
