parameters:
#    quak_shops_admin.example.class: Quak\ShopsAdminBundle\Example

services:
#    quak_shops_admin.example:
#        class: %quak_shops_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
