parameters:
    form.report.class: Quak\ShopsReportBundle\Form\Type\ReportType

services:
    form.report:
        class: %form.report.class%
        arguments:
            formFieldRepository: @repository.formField
