parameters:
#    quak_shops_report.example.class: Quak\ShopsReportBundle\Example

services:
#    quak_shops_report.example:
#        class: %quak_shops_report.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
